---
title: "instrument_evaluation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{instrument_evaluation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


###  previous code
```

  ### retrieve PAVE2  result from data set
  {

    all.pave <- dir("d:/data/2025.12.26.PAVE2/PAVE_With_Params/",
                    pattern = "ppm10_sn10.rdata",full.names = T)
    res <- list()
    for (i in seq_along(all.pave)) {

      f <- all.pave[i]
      obj <- MSdev_load(f)
      message_with_time(i,", TRACE on ",basename(f))
      #try(        obj <- PAVE2(obj)      )
      res[[basename(f)]] <- obj
      message_with_time("save ",basename(f))
      if(!"pave_cn_seed" %in% names(obj@statData$PAVE2$Negative))
        message("error")
      #saveRDS(res,file = "d:/temp/PAVE_TEMP_20251125.rds")

    }
    res.parse <- list()
    for (i in seq_along(res)) {

      i.res.neg <- data.frame(res[[i]]@statData$TRACE$Negative)
      i.res.pos <- data.frame(res[[i]]@statData$TRACE$Positive)
      if(nrow(i.res.neg)==0) next
      #i.res.neg <-  dplyr::filter(i.res.neg,feature_id == seed)
      #i.res.pos <- dplyr::filter(i.res.pos,feature_id == seed)

      i.anno.count.pos <- c(table(i.res.pos$type),
        total.peaks = nrow(featureDefinitions(res[[i]]@xcmsData$PositiveMS1)),
        formula.matched = sum(!is.na(i.res.pos$compound_id)),
        rt.matched = sum(abs(i.res.pos$compound.rt-i.res.pos$rt) < 120,na.rm = T))
      i.pos <- data.frame(
        polarity = "Positive",
        instru = names(res)[i],
        trace_annotation = names(i.anno.count.pos),
        count = unname(i.anno.count.pos),
        total.peaks = unname( i.anno.count.pos["total.peaks"]),
        mz.dyn = res[[i]]@statData$PAVE2_temp$Positive$mz.dyn$pi,
        rt.dyn = res[[i]]@statData$PAVE2_temp$Positive$rt.dyn$pi
      )
      i.anno.count.neg <- c(table(i.res.neg$type),
                            total.peaks = nrow(featureDefinitions(res[[i]]@xcmsData$NegativeMS1)),
                            formula.matched = sum(!is.na(i.res.neg$compound_id)),
                            rt.matched = sum(abs(i.res.neg$compound.rt-i.res.neg$rt) < 120,na.rm = T))
      i.neg <- data.frame(
        polarity = "Negative",
        instru = names(res)[i],
        trace_annotation = names(i.anno.count.neg),
        count = unname(i.anno.count.neg),
        total.peaks = unname( i.anno.count.neg["total.peaks"]),
        mz.dyn = res[[i]]@statData$PAVE2_temp$Negative$mz.dyn$pi,
        rt.dyn = res[[i]]@statData$PAVE2_temp$Negative$rt.dyn$pi
      )

      res.parse[[i]] <- rbind(i.pos,i.neg)


    }

    instru.manu <- setNames(c("Thermo","Thermo","Thermo","Thermo","Thermo","Thermo","Thermo",
                              "Thermo","Thermo","Thermo","Thermo"),
                            nm = c("Ascend","Astral","OE480_480k","OE480_240k","OE480_120k","OE480_60k","QE_Plus",
                                   "Exd_120K_eDR","Exd_120K_NoneDR","Exd_240K_eDR","Exd_480K_eDR"))


    res.parse.df <- rbindlist(res.parse)%>%
      dplyr::mutate(instru.name = sub("_ppm.*", "", instru),
                    ppm = sub(".*_ppm([0-9]+).*", "\\1", instru),
                    sn = sub(".*_sn([0-9]+).*", "\\1", instru),
                    manu = instru.manu[instru.name])%>%
      dplyr::filter(ppm == "10",sn == "10"  )%>%
      dplyr::filter(!instru.name%in% c("Exd_480K_eDR"))%>%
      #dplyr::filter(! ppm %in% c("100","10"))%>%
      dplyr::mutate(ratio = count / total.peaks,
                    instru.name = factor(
                      instru.name,
                      levels = c("QE_Plus",
                                 "OE480_60k","OE480_120k","OE480_240k","OE480_480k",
                                 "Ascend","Astral",
                                 "Exd_120K_NoneDR", "Exd_120K_eDR","Exd_240K_eDR"
                                 )),
                    trace_annotation = factor(
                      trace_annotation,
                      levels = c(#"CN_metabolite","Unknow_adduct",
                        "total.peaks", "isotope","fragment", "adduct", "metabolite",
                        "formula.matched","rt.matched")))%>%
      dplyr::arrange(instru.name,polarity,trace_annotation   )



  }

  ### composition
  {

    fill_cols <- c(
      "adduct"         = "#00A087",  # blue (chemical association)
      "metabolite"  = "#E64B35",  # green (biological meaning)
      "fragment"       = "#F39B7F",  # vermillion (breakage)
      "isotope"        = "#3C5488",  # sky blue (mass shift)
      "total.peaks" = "grey"
     # "Unknow_adduct"  = "#CC79A7",  # purple (uncertain)
     # "noise"          = "#aaaaaa"   # orange (background)
    )
    fill_labs <- c(
      "adduct"         = "Adduct",  # blue (chemical association)
      "metabolite"  = "CN metabolite",  # green (biological meaning)
      "fragment"       = "Fragment",  # vermillion (breakage)
      "isotope"        = "Isotope",  # sky blue (mass shift)
      "total.peaks" = "Others"
      #"Unknow_adduct"  = "Unknown adduct",  # purple (uncertain)
      #"noise"          = "Noise"   # orange (background)
    )

    p.comp.pos <- ggplot()+
      geom_bar(data = filter(res.parse.df,
                             polarity == "Positive",
                             trace_annotation %in% c("total.peaks")
                             ),
               aes(x = instru.name, y = ratio ,
                   fill = trace_annotation ),
               show.legend = T,
               col = "black",
               stat = "identity")+
      geom_bar(data = filter(res.parse.df,
                             polarity == "Positive",
                             trace_annotation %in% c("metabolite","fragment","adduct","isotope")),
               aes(x = instru.name, y = ratio ,
                   fill = trace_annotation ),
               show.legend = T,
               col = "black",
               stat = "identity")+
      scale_fill_manual(values = fill_cols,labels = fill_labs)+
      scale_y_reverse(breaks = seq(0,0.05,0.01),
                      labels = 1- seq(0,0.05,0.01) )+
      labs(x = "",y = "Ratio",title = "Positive",fill = "TRACE\nAnnotation")+
      coord_cartesian(ylim = c(0, 0.05))+
      guides(fill = guide_legend(reverse = TRUE))+
      theme_bw(base_size = 6)+
      theme(axis.text.x = element_text(angle = -30,hjust = 0))

    p.comp.neg <- ggplot()+
      geom_bar(data = filter(res.parse.df,
                             polarity == "Negative",
                             trace_annotation %in% c("total.peaks")
      ),
      aes(x = instru.name, y = ratio ,
          fill = trace_annotation ),
      show.legend = T,
      col = "black",
      stat = "identity")+
      geom_bar(data = filter(res.parse.df,
                             polarity == "Negative",
                             trace_annotation %in% c("metabolite","fragment","adduct","isotope")),
               aes(x = instru.name, y = ratio ,
                   fill = trace_annotation ),
               show.legend = T,
               col = "black",
               stat = "identity")+
      scale_fill_manual(values = fill_cols,labels = fill_labs)+
      scale_y_reverse(breaks = seq(0,0.05,0.01),
                      labels = 1- seq(0,0.05,0.01) )+
      labs(x = "",y = "Ratio",title = "Positive",fill = "TRACE\nAnnotation")+
      coord_cartesian(ylim = c(0, 0.08))+
      guides(fill = guide_legend(reverse = TRUE))+
      theme_bw(base_size = 6)+
      theme(axis.text.x = element_text(angle = -30,hjust = 0))

    p.comp <- p.comp.pos+p.comp.neg+
      plot_layout(widths = c(0.5,0.5),guides = "collect")&
      theme(legend.key.size = unit(0.15,"inch"))
    open_plot_win(p.comp,6,3)

  }


  ### trend
  {
    cols11 <- c(
      "#E69F00",  # orange
      "#56B4E9",  # sky blue
      "#009E73",  # bluish green
      "#F0E442",  # yellow
      "#0072B2",  # blue
      "#D55E00",  # vermillion
      "#CC79A7",  # reddish purple
      "#1B9E77",  # dark green
      "#A6761D",  # brown
      "#6A3D9A",  # purple
      "#B15928"   # dark orange
    )

    trend.df <- res.parse.df %>%
      #dplyr::mutate(count = total.peaks - count)%>%
      dplyr::filter(trace_annotation == "metabolite")%>%
      dplyr::distinct(instru.name,polarity,total.peaks,count)
    axis.scale = 30

    p.trend.pos <- ggplot(filter(trend.df,polarity == "Positive"))+
      geom_bar(aes( x = instru.name , y = total.peaks,fill = instru.name) ,
               col = "black",stat = "identity",show.legend = T)+
      geom_point(aes(x = instru.name , y = count * axis.scale ),
                 fill = "white" ,stroke  = 1.5,pch = 21 ,size = 2)+
      geom_line(aes(x = instru.name , y = count * axis.scale,group = 1))+
      scale_y_continuous(
        name = "Total peaks count",
        sec.axis = sec_axis(~ . /axis.scale, name = "Labeled peaks count")
      ) +
      scale_fill_manual(values = cols11)+
      labs(x = "",y = "Ratio",title = "Positive",fill = "Instrument")+
      theme_bw(base_size = 6)+
      theme(axis.text.x = element_text(angle = -30,hjust = 0))
    p.trend.pos


    axis.scale = 20
    p.trend.neg <- ggplot(filter(trend.df,polarity == "Negative"))+
      geom_bar(aes( x = instru.name , y = total.peaks,fill = instru.name) ,
               col = "black",stat = "identity")+
      geom_point(aes(x = instru.name , y = count * axis.scale ),
                 fill = "white" ,stroke  = 1.5,pch = 21 ,size = 2) +
      geom_line(aes(x = instru.name , y = count * axis.scale,group = 1)) +
      scale_y_continuous(
        name = "Total peaks count",
        sec.axis = sec_axis(~ . /axis.scale, name = "Labeled peaks count")
      ) +
      scale_fill_manual(values = cols11)+
      labs(x = "",y = "Ratio",title = "Negative",fill = "Instrument")+
      theme_bw(base_size = 6)+
      theme(axis.text.x = element_text(angle = -30,hjust = 0))
    p.trend.neg

    p <- p.trend.pos + p.trend.neg+plot_layout(guides = "collect")&
      theme(legend.key.size = unit(0.15,"inch"))
    open_plot_win(p,6,3)

  }


  ### peaks - CN metabolites ratio
  {



    p.peak.ratio <- ggplot(filter(res.parse.df,
                                  trace_annotation == "metabolite"))+
      geom_point(aes(x = total.peaks , y = ratio ,
                     #size = polarity,
                     fill = polarity),
                 size = 2,
                 show.legend = T,pch = 21)+
      scale_x_log10()+
      scale_y_continuous(labels = scales::percent_format())+
      scale_fill_manual(values = c("#3C5488","#E64B35"))+
      labs(x = "Peaks count", y = "CN metabolte ratio",fill = "Ion mode")+
      theme_bw(base_size = 6)+
      theme(legend.key.size = unit(0.1,"inch"),
            legend.box.background = element_rect(color  = "grey",fill = "transparent"),
            legend.position = c(0.98,0.98),
            #legend.position = "right",
            legend.justification = c(1, 1)
      )

    p.peak.ratio
    open_plot_win(p.peak.ratio,3,3)

  }

  ### peaks - dyn ratio
  {

    cols11 <- c(
      "#E69F00",  # orange
      "#56B4E9",  # sky blue
      "#009E73",  # bluish green
      "#F0E442",  # yellow
      "#0072B2",  # blue
      "#D55E00",  # vermillion
      "#CC79A7",  # reddish purple
      "#1B9E77",  # dark green
      "#A6761D",  # brown
      "#6A3D9A",  # purple
      "#B15928"   # dark orange
    )

    p.dyn.ratio <- ggplot(filter(res.parse.df,
                                 trace_annotation == "metabolite"))+
      geom_point(aes(x = total.peaks , y =  mz.dyn , fill = polarity),
                 show.legend = F,
                 pch = 21,size= 2)+
      scale_x_log10( )+
      scale_fill_manual(values = c("#3C5488","#E64B35"))+
      #scale_fill_manual(values = cols11)+
      labs(x = "Peaks count", y = "Estimated mixing proportion (π)",fill = "Instrument")+
      theme_bw(base_size = 6)+
      theme(legend.key.size = unit(0.1,"inch"),
            legend.box.background = element_rect(color  = "grey",fill = "transparent"),
            legend.position = c(0.98,0.98),
            legend.justification = c(1, 1))

    p.dyn.ratio
    open_plot_win(p.dyn.ratio,3,3)

  }


  ### merge pos and neg
  {

    res.parse.df.merged <- res.parse.df%>%
      dplyr::group_by(instru,trace_annotation)%>%
      dplyr::mutate(count = sum(count),
                    total.peaks = sum(total.peaks),
                    ratio  = count/total.peaks)%>%
      dplyr::distinct(instru,pave_annotation,.keep_all = T)

    p.comp.merged <- ggplot(filter(res.parse.df,polarity == "Negative"))+
      geom_bar(aes(x = instru.name, y = ratio ,
                   fill = pave_annotation ),
               col = "black",
               stat = "identity")+
      scale_fill_manual(values = fill_cols,labels = fill_labs)+
      labs(x = "",y = "Ratio",title = "Total",fill = "TRACE\nAnnotation")+
      coord_cartesian(ylim = c(0.9, 1))+
      theme_bw(base_size = 6)+
      theme(axis.text.x = element_text(angle = -30,hjust = 0),
            legend.key.size = unit(0.15,"inch"))



    trend.df <- res.parse.df.merged%>%
      #dplyr::mutate(count = total.peaks - count)%>%
      dplyr::filter(pave_annotation == "CN_metabolite")%>%
      dplyr::distinct(instru.name,polarity,total.peaks,count)

    p.trend.merged <- ggplot((trend.df))+
      geom_bar(aes( x = instru.name , y = total.peaks,fill = instru.name) ,
               col = "black",stat = "identity")+
      geom_point(aes(x = instru.name , y = count * axis.scale ),
                 fill = "white" ,stroke  = 1.5,pch = 21 ,size = 2) +
      geom_line(aes(x = instru.name , y = count * axis.scale,group = 1)) +
      scale_y_continuous(
        name = "Total peaks count",
        sec.axis = sec_axis(~ . /axis.scale, name = "Labeled peaks count")
      ) +
      scale_fill_manual(values = cols11)+
      labs(x = "",y = "Ratio",title = "Total",fill = "Instrument")+
      theme_bw(base_size = 6)+
      theme(axis.text.x = element_text(angle = -30,hjust = 0),
            legend.key.size = unit(0.15,"inch"))
    p.trend.merged

    p1 <- (p.comp.merged/p.trend.merged)+
      plot_annotation(tag_levels = "A")&
      theme(
        plot.title = element_text(size = 0),
        legend.key.size = unit(0.1,"inch"),
        plot.tag = element_text(size = 12,face = "plain",vjust  =  0),
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0),
        axis.text.x = element_text(angle = -30,hjust = 0),
        plot.margin = margin(t = 0, r = 0, b = 0, l = 1)
      )

    open_plot_win(p1,3.2,4)

  }

  ### patchwork Figure 4
  {

    p1 <- (p.trend.pos/p.comp.pos)+
      plot_annotation(tag_levels = "A")&
      theme(
        plot.title = element_text(size = 0),
        legend.key.size = unit(0.1,"inch"),
        plot.tag = element_text(size = 12,face = "plain",vjust  =  0),
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0),
        axis.text.x = element_text(angle = -30,hjust = 0),
        plot.margin = margin(t = 0, r = 0, b = 0, l = 1)
      )

    open_plot_win(p1,3.2,4)
    open_plot_ppt(p1,3.2,4)

    p2 <- p.dyn.ratio+p.peak.ratio



    open_plot_win(p2,3.2,1.6)
    open_plot_ppt(p2,3.2,1.6)

  }

  ### patchwork Figure S
  {

    p <- (p.trend.neg/p.comp.neg)+
      plot_annotation(tag_levels = "A")&
      theme(
        plot.title = element_text(size = 0),
        legend.key.size = unit(0.1,"inch"),
        plot.tag = element_text(size = 12,face = "plain",vjust  =  0),
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0),
        axis.text.x = element_text(angle = -30,hjust = 0),
        plot.margin = margin(t = 0, r = 0, b = 0, l = 1)
      )
    #p
    open_plot_win(p,3.2,4)
    open_plot_ppt(p,3.2,4)



  }




  ### table
  {

    trend.df <- res.parse.df%>%
      #dplyr::mutate(count = total.peaks - count)%>%
      dplyr::filter(polarity == "Positive")%>%
      dplyr::distinct(instru.name,trace_annotation,polarity,total.peaks,count)%>%
      dplyr::group_by(instru.name,trace_annotation)%>%
      dplyr::mutate(pol.sum = sum(count) ,
                    total.peaks = sum(total.peaks))%>%
      dplyr::ungroup()%>%
      dplyr::distinct(instru.name, trace_annotation , pol.sum )%>%
      dplyr::select(instru.name,trace_annotation ,pol.sum )%>%
      pivot_wider(names_from =  instru.name, values_from = pol.sum)

    edit_df_in_excel(trend.df)

  }


```




### reviewers' comments
```
Please provide key information in Supplementary Table 3, including, for each instrument, the count of CN patterns with p > 0.75, the count of dynamic filter, the count of formula matched, the count of RT matched, and any other relevant metrics.

```

### table generate here

Supplementary Table 3: per-instrument TRACE summary metrics by ion mode (Negative / Positive sheets; read-only load via `MSdev_load()`).

```{r supp-table-3}
library(dplyr)
library(tidyr)
library(data.table)
library(MSdev)

.instru_metrics_one_pol <- function(obj, pol) {
  trace.df <- tryCatch(
    as.data.frame(obj@advancedAna$TRACE[[pol]]),
    error = function(e) NULL
  )
  if (is.null(trace.df) || !nrow(trace.df)) {
    trace.df <- tryCatch(
      as.data.frame(obj@statData$TRACE[[pol]]),
      error = function(e) NULL
    )
  }
  if (is.null(trace.df) || !nrow(trace.df)) {
    return(NULL)
  }

  get_pol_temp <- function(key) {
    val <- tryCatch(obj@advancedAna$TRACE_temp[[pol]][[key]], error = function(e) NULL)
    if (is.null(val)) {
      val <- tryCatch(obj@advancedAna$PAVE2_temp[[pol]][[key]], error = function(e) NULL)
    }
    val
  }

  cn.finder <- get_pol_temp("CNfinder")
  cn.hit.post <- get_pol_temp("cn.net.hit")
  cn.finder <- if (is.null(cn.finder)) data.table::data.table() else data.table::as.data.table(cn.finder)
  cn.hit.post <- if (is.null(cn.hit.post)) data.table::data.table() else data.table::as.data.table(cn.hit.post)

  cor.col <- intersect(c("TRACE_cor", "pave_cor"), names(cn.finder))[1]
  if (is.na(cor.col) || !nrow(cn.finder)) {
    cn.p075 <- data.table::data.table()
  } else {
    cn.p075 <- cn.finder[
      is.finite(get(cor.col)) & get(cor.col) > 0.75
    ]
  }

  seeds.p075 <- unique(cn.p075$from)

  get_dyn_fit <- function(key) {
    val <- tryCatch(obj@advancedAna$PAVE2_temp[[pol]][[key]], error = function(e) NULL)
    if (is.null(val)) {
      val <- tryCatch(obj@advancedAna$TRACE_temp[[pol]][[key]], error = function(e) NULL)
    }
    val
  }
  mz.fit <- get_dyn_fit("mz.dyn")
  rt.fit <- get_dyn_fit("rt.dyn")
  ppm.dyn <- if (!is.null(mz.fit$sd)) {
    as.numeric(mz.fit$sd) * stats::qnorm(0.999)
  } else {
    NA_real_
  }
  rt.tol.dyn <- if (!is.null(rt.fit$sd)) {
    as.numeric(rt.fit$sd) * stats::qnorm(0.999)
  } else {
    NA_real_
  }

  if (nrow(cn.hit.post)) {
    seeds.retained <- unique(cn.hit.post$from)
  } else if (nrow(cn.p075) && is.finite(ppm.dyn) && is.finite(rt.tol.dyn)) {
    cn.net.filter <- cn.p075[
      abs(mz.ppm) > ppm.dyn | abs(rt.diff) > rt.tol.dyn
    ]
    seeds.retained <- setdiff(
      as.character(seeds.p075),
      as.character(unique(cn.net.filter$from))
    )
  } else {
    seeds.retained <- character(0)
  }

  xcms.slot <- if (pol == "Negative") "NegativeMS1" else "PositiveMS1"

  data.frame(
    polarity = pol,
    total_peaks = nrow(xcms::featureDefinitions(obj@xcmsData[[xcms.slot]])),
    cn_pattern_p_gt_0.75 = nrow(cn.p075),
    cn_seed_p_gt_0.75 = length(seeds.p075),
    cn_seed_dynamic_filtered = length(setdiff(
      as.character(seeds.p075),
      as.character(seeds.retained)
    )),
    cn_seed_retained = length(seeds.retained),
    metabolite = sum(trace.df$type == "metabolite", na.rm = TRUE),
    adduct = sum(trace.df$type == "adduct", na.rm = TRUE),
    fragment = sum(trace.df$type == "fragment", na.rm = TRUE),
    isotope = sum(trace.df$type == "isotope", na.rm = TRUE),
    formula_matched = sum(!is.na(trace.df$compound_id), na.rm = TRUE),
    rt_matched = sum(
      abs(trace.df$compound.rt - trace.df$rt) < 120,
      na.rm = TRUE
    ),
    mz_dyn_cutoff_ppm = ppm.dyn,
    rt_dyn_cutoff_s = rt.tol.dyn,
    stringsAsFactors = FALSE
  )
}

.instru_metrics_one_file <- function(obj, instru) {
  pol.metrics <- lapply(
    c("Negative", "Positive"),
    function(pol) .instru_metrics_one_pol(obj, pol)
  )
  pol.metrics <- pol.metrics[!vapply(pol.metrics, is.null, logical(1))]
  if (!length(pol.metrics)) {
    return(NULL)
  }

  dplyr::bind_rows(pol.metrics) %>%
    dplyr::mutate(instru = instru)
}

.supp3_to_wide <- function(df, polarity) {
  metric.levels <- c(
    "total_peaks",
    "cn_pattern_p_gt_0.75",
    "cn_seed_p_gt_0.75",
    "cn_seed_dynamic_filtered",
    "cn_seed_retained",
    "metabolite",
    "adduct",
    "fragment",
    "isotope",
    "formula_matched",
    "rt_matched",
    "mz_dyn_cutoff_ppm",
    "rt_dyn_cutoff_s"
  )

  df %>%
    dplyr::filter(polarity == !!polarity) %>%
    dplyr::select(
      instru.name,
      dplyr::all_of(metric.levels)
    ) %>%
    tidyr::pivot_longer(
      cols = -instru.name,
      names_to = "metric",
      values_to = "count"
    ) %>%
    dplyr::mutate(metric = factor(metric, levels = metric.levels)) %>%
    dplyr::arrange(metric) %>%
    tidyr::pivot_wider(
      names_from = instru.name,
      values_from = count
    )
}

.edit_supp3_in_excel <- function(df.list) {
  wb <- openxlsx::createWorkbook()
  for (i in seq_along(df.list)) {
    sheet.name <- gsub("[:;/]", "_", names(df.list)[i])
    openxlsx::addWorksheet(wb, sheetName = sheet.name)
    openxlsx::writeData(
      wb,
      sheet = i,
      x = df.list[[i]],
      rowNames = TRUE,
      na.string = NA
    )
  }
  temp.xlsx <- file.path(
    tempdir(),
    paste0("SuppTable3_", paste0(sample(letters, 6L), collapse = ""), ".xlsx")
  )
  openxlsx::saveWorkbook(wb, file = temp.xlsx)
  openxlsx::openXL(temp.xlsx)
  invisible(df.list)
}

{
  all.pave <- dir(
    "d:/data/2025.12.26.PAVE2/PAVE_With_Params/",
    pattern = "ppm10_sn10.rdata",
    full.names = TRUE
  )

  instru.manu <- setNames(
    c(
      "Thermo", "Thermo", "Thermo", "Thermo", "Thermo", "Thermo", "Thermo",
      "Thermo", "Thermo", "Thermo", "Thermo"
    ),
    nm = c(
      "Ascend", "Astral", "OE480_480k", "OE480_240k", "OE480_120k", "OE480_60k", "QE_Plus",
      "Exd_120K_eDR", "Exd_120K_NoneDR", "Exd_240K_eDR", "Exd_480K_eDR"
    )
  )

  supp3.list <- lapply(seq_along(all.pave), function(i) {
    obj <- MSdev_load(all.pave[i])
    obj <- MSdev:::.update_MSdev_object(obj)
    .instru_metrics_one_file(obj, basename(all.pave[i]))
  })
  supp3.list <- supp3.list[!vapply(supp3.list, is.null, logical(1))]

  supp3.df <- dplyr::bind_rows(supp3.list) %>%
    dplyr::mutate(
      instru.name = sub("_ppm.*", "", instru),
      ppm = sub(".*_ppm([0-9]+).*", "\\1", instru),
      sn = sub(".*_sn([0-9]+).*", "\\1", instru),
      manufacturer = instru.manu[instru.name],
      instru.name = factor(
        instru.name,
        levels = c(
          "QE_Plus",
          "OE480_60k", "OE480_120k", "OE480_240k", "OE480_480k",
          "Ascend", "Astral",
          "Exd_120K_NoneDR", "Exd_120K_eDR", "Exd_240K_eDR"
        )
      )
    ) %>%
    dplyr::filter(ppm == "10", sn == "10") %>%
    dplyr::filter(!instru.name %in% c("Exd_480K_eDR")) %>%
    dplyr::arrange(polarity, instru.name) %>%
    dplyr::mutate(instru.name = as.character(instru.name)) %>%
    dplyr::filter(!is.na(instru.name), nzchar(instru.name))

  supp3.table3 <- list(
    Negative = .supp3_to_wide(supp3.df, "Negative"),
    Positive = .supp3_to_wide(supp3.df, "Positive")
  )

  if (interactive()) {
    .edit_supp3_in_excel(supp3.table3)
  }
  supp3.table3
}
```
